// Languages with an ISO 639-1 code, from social-app's src/locale/languages.ts
export const POST_LANGUAGES = [
  { code2: "aa", name: "Afar" },
  { code2: "ab", name: "Abkhazian" },
  { code2: "af", name: "Afrikaans" },
  { code2: "ak", name: "Akan" },
  { code2: "sq", name: "Albanian" },
  { code2: "am", name: "Amharic" },
  { code2: "ar", name: "Arabic" },
  { code2: "an", name: "Aragonese" },
  { code2: "hy", name: "Armenian" },
  { code2: "as", name: "Assamese" },
  { code2: "av", name: "Avaric" },
  { code2: "ae", name: "Avestan" },
  { code2: "ay", name: "Aymara" },
  { code2: "az", name: "Azerbaijani" },
  { code2: "ba", name: "Bashkir" },
  { code2: "bm", name: "Bambara" },
  { code2: "eu", name: "Basque" },
  { code2: "be", name: "Belarusian" },
  { code2: "bn", name: "Bangla" },
  { code2: "bh", name: "Bhojpuri" },
  { code2: "bi", name: "Bislama" },
  { code2: "bo", name: "Tibetan" },
  { code2: "bs", name: "Bosnian" },
  { code2: "br", name: "Breton" },
  { code2: "bg", name: "Bulgarian" },
  { code2: "my", name: "Burmese" },
  { code2: "ca", name: "Catalan" },
  { code2: "cs", name: "Czech" },
  { code2: "ch", name: "Chamorro" },
  { code2: "ce", name: "Chechen" },
  { code2: "zh", name: "Chinese" },
  { code2: "cu", name: "Church Slavic" },
  { code2: "cv", name: "Chuvash" },
  { code2: "kw", name: "Cornish" },
  { code2: "co", name: "Corsican" },
  { code2: "cr", name: "Cree" },
  { code2: "cy", name: "Welsh" },
  { code2: "da", name: "Danish" },
  { code2: "de", name: "German" },
  { code2: "dv", name: "Divehi" },
  { code2: "nl", name: "Dutch" },
  { code2: "dz", name: "Dzongkha" },
  { code2: "el", name: "Greek" },
  { code2: "en", name: "English" },
  { code2: "eo", name: "Esperanto" },
  { code2: "et", name: "Estonian" },
  { code2: "ee", name: "Ewe" },
  { code2: "fo", name: "Faroese" },
  { code2: "fa", name: "Persian" },
  { code2: "fj", name: "Fijian" },
  { code2: "fi", name: "Finnish" },
  { code2: "fr", name: "French" },
  { code2: "fy", name: "Western Frisian" },
  { code2: "ff", name: "Fulah" },
  { code2: "ka", name: "Georgian" },
  { code2: "gd", name: "Scottish Gaelic" },
  { code2: "ga", name: "Irish" },
  { code2: "gl", name: "Galician" },
  { code2: "gv", name: "Manx" },
  { code2: "gn", name: "Guarani" },
  { code2: "gu", name: "Gujarati" },
  { code2: "ht", name: "Haitian Creole" },
  { code2: "ha", name: "Hausa" },
  { code2: "he", name: "Hebrew" },
  { code2: "hz", name: "Herero" },
  { code2: "hi", name: "Hindi" },
  { code2: "ho", name: "Hiri Motu" },
  { code2: "hr", name: "Croatian" },
  { code2: "hu", name: "Hungarian" },
  { code2: "ig", name: "Igbo" },
  { code2: "is", name: "Icelandic" },
  { code2: "io", name: "Ido" },
  { code2: "ii", name: "Sichuan Yi; Nuosu" },
  { code2: "iu", name: "Inuktitut" },
  { code2: "ie", name: "Interlingue" },
  { code2: "ia", name: "Interlingua" },
  { code2: "id", name: "Indonesian" },
  { code2: "ik", name: "Inupiaq" },
  { code2: "it", name: "Italian" },
  { code2: "jv", name: "Javanese" },
  { code2: "ja", name: "Japanese" },
  { code2: "kl", name: "Kalaallisut" },
  { code2: "kn", name: "Kannada" },
  { code2: "ks", name: "Kashmiri" },
  { code2: "kr", name: "Kanuri" },
  { code2: "kk", name: "Kazakh" },
  { code2: "km", name: "Khmer" },
  { code2: "ki", name: "Kikuyu; Gikuyu" },
  { code2: "rw", name: "Kinyarwanda" },
  { code2: "ky", name: "Kyrgyz" },
  { code2: "kv", name: "Komi" },
  { code2: "kg", name: "Kongo" },
  { code2: "ko", name: "Korean" },
  { code2: "kj", name: "Kuanyama; Kwanyama" },
  { code2: "ku", name: "Kurdish" },
  { code2: "lo", name: "Lao" },
  { code2: "la", name: "Latin" },
  { code2: "lv", name: "Latvian" },
  { code2: "li", name: "Limburgish" },
  { code2: "ln", name: "Lingala" },
  { code2: "lt", name: "Lithuanian" },
  { code2: "lb", name: "Luxembourgish" },
  { code2: "lu", name: "Luba-Katanga" },
  { code2: "lg", name: "Ganda" },
  { code2: "mk", name: "Macedonian" },
  { code2: "mh", name: "Marshallese" },
  { code2: "ml", name: "Malayalam" },
  { code2: "mi", name: "Māori" },
  { code2: "mr", name: "Marathi" },
  { code2: "ms", name: "Malay" },
  { code2: "mg", name: "Malagasy" },
  { code2: "mt", name: "Maltese" },
  { code2: "mn", name: "Mongolian" },
  { code2: "na", name: "Nauru" },
  { code2: "nv", name: "Navajo" },
  { code2: "nr", name: "South Ndebele" },
  { code2: "nd", name: "North Ndebele" },
  { code2: "ng", name: "Ndonga" },
  { code2: "ne", name: "Nepali" },
  { code2: "nn", name: "Norwegian Nynorsk" },
  { code2: "nb", name: "Norwegian Bokmål" },
  { code2: "no", name: "Norwegian" },
  { code2: "ny", name: "Nyanja" },
  { code2: "oc", name: "Occitan" },
  { code2: "oj", name: "Ojibwa" },
  { code2: "or", name: "Odia" },
  { code2: "om", name: "Oromo" },
  { code2: "os", name: "Ossetic" },
  { code2: "pa", name: "Punjabi" },
  { code2: "pi", name: "Pali" },
  { code2: "pl", name: "Polish" },
  { code2: "pt", name: "Portuguese" },
  { code2: "ps", name: "Pashto" },
  { code2: "qu", name: "Quechua" },
  { code2: "rm", name: "Romansh" },
  { code2: "ro", name: "Romanian" },
  { code2: "rn", name: "Rundi" },
  { code2: "ru", name: "Russian" },
  { code2: "sg", name: "Sango" },
  { code2: "sa", name: "Sanskrit" },
  { code2: "si", name: "Sinhala" },
  { code2: "sk", name: "Slovak" },
  { code2: "sl", name: "Slovenian" },
  { code2: "se", name: "Northern Sami" },
  { code2: "sm", name: "Samoan" },
  { code2: "sn", name: "Shona" },
  { code2: "sd", name: "Sindhi" },
  { code2: "so", name: "Somali" },
  { code2: "st", name: "Southern Sotho" },
  { code2: "es", name: "Spanish" },
  { code2: "sc", name: "Sardinian" },
  { code2: "sr", name: "Serbian" },
  { code2: "ss", name: "Swati" },
  { code2: "su", name: "Sundanese" },
  { code2: "sw", name: "Swahili" },
  { code2: "sv", name: "Swedish" },
  { code2: "ty", name: "Tahitian" },
  { code2: "ta", name: "Tamil" },
  { code2: "tt", name: "Tatar" },
  { code2: "te", name: "Telugu" },
  { code2: "tg", name: "Tajik" },
  { code2: "tl", name: "Filipino" },
  { code2: "th", name: "Thai" },
  { code2: "ti", name: "Tigrinya" },
  { code2: "to", name: "Tongan" },
  { code2: "tn", name: "Tswana" },
  { code2: "ts", name: "Tsonga" },
  { code2: "tk", name: "Turkmen" },
  { code2: "tr", name: "Turkish" },
  { code2: "tw", name: "Akan" },
  { code2: "ug", name: "Uyghur" },
  { code2: "uk", name: "Ukrainian" },
  { code2: "ur", name: "Urdu" },
  { code2: "uz", name: "Uzbek" },
  { code2: "ve", name: "Venda" },
  { code2: "vi", name: "Vietnamese" },
  { code2: "vo", name: "Volapük" },
  { code2: "wa", name: "Walloon" },
  { code2: "wo", name: "Wolof" },
  { code2: "xh", name: "Xhosa" },
  { code2: "yi", name: "Yiddish" },
  { code2: "yo", name: "Yoruba" },
  { code2: "za", name: "Zhuang; Chuang" },
  { code2: "zu", name: "Zulu" },
];

export const POST_LANGUAGE_CODES = new Set(
  POST_LANGUAGES.map((language) => language.code2),
);

export const POST_LANGUAGE_NAMES = new Map(
  POST_LANGUAGES.map((language) => [language.code2, language.name]),
);
